public class Main {
    public static void main(String[] args) {
//        Sum_result sumResult = new Sum_result();
//        sumResult.summa();

        Methods.div(6, 0);
        Methods.div(6, 3);
        Methods.mult(5, 5);
        Methods.mult(0, 0);
        Methods.plus(4, 6);
        Methods.minus(8, 3);
    }
}

// не понимаю почему при использовании MyException результат всегда NULL